# swagger.yml
openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for user registration, login, and profile management
servers:
  - url: http://localhost:3000/
paths:
  /api/users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                number:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request
        '500':
          description: Server error
  /api/users/login:
    post:
      summary: Login as an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Logged in successfully
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Server error
  /api/users/profile:
    get:
      summary: Get user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
        '401':
          description: Unauthorized
        '500':
          description: Server error
    put:
      summary: Update user profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                number:
                  type: string
      responses:
        '200':
          description: User profile updated successfully
        '401':
          description: Unauthorized
        '500':
          description: Server error
    delete:
      summary: Delete user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile deleted successfully
        '401':
          description: Unauthorized
        '500':
          description: Server error
